platform :ios, '9.0'

target 'AppleLogo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AppleLogo

  target 'AppleLogoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AppleLogoUITests' do
    inherit! :search_paths
    # Pods for testing
  end
  
  pod 'SnapKit'

end
